### ISSUE TITLE
Create table of contents

### ISSUE THREAD

**Issue by prete** [cellgeni/references#1]
Create a list of species/reference and link them to the headings that are currently there (ie: `[reference title](#header-anchor)`)

_Examaple:_

- **Human**
  - [2020A Full](#2020A-Full) 
  - [2020A plus Plasmodium_Falciparum.EPr1.37](#2020A-plus-Plasmodium_Falciparum.EPr1.37 )
  - [GRCh38-1.2.0](#GRCh38-1.2.0)
  - [Gencode v19 Full](#Gencode-v19-Full)
- **Mouse**
  - [2020A Full](#2020A-Full) 
  - [2.1.0](#2.1.0)

**Comment by gabypires** [comment]
implemented
